Add dbt build command as an operator
community-tech-alliance/airflow-dbt pull request #3
Opened 2023-09-25 13:56 UTC by annabaringer

Hi y'all! Thanks for maintaining this repo! 

This PR added an operator for dbt's build command. 

cc: @jackwelty from my team

2023-09-29 19:46 UTC, emily-flambe commented on README.md
> +There are six operators currently implemented:
🎉

2023-09-29 19:48 UTC, emily-flambe approved these changes
Sick!! Looks good to me, assuming you've tested it and etc. you have my blessing to merge this in! 🇺🇸 🇺🇸 🇺🇸

2023-09-29 19:50 UTC, emily-flambe commented
qq @annabaringer and @jackwelty, are y'all using the pypi distribution of this? If so then we can make a new release after this is merged in so that you can use this Cool New Functionality to achieve your goals ✨

2023-09-29 19:54 UTC, jitoquinto requested changes
Sweet! Thank you for contributing! One ask though, could you bump the version number on the `airflow_dbt_cta/__version__.py` file? It would just be like [this commit](https://github.com/community-tech-alliance/airflow-dbt/commit/daceb11553f2ba98a3ed43c2579ad039bdc235d2)!

2023-10-02 14:23 UTC, jitoquinto approved these changes
Awesome thank you!! 🚀

2023-10-03 17:45 UTC, jitoquinto commented
> > qq @annabaringer and @jackwelty, are y'all using the pypi distribution of this? If so then we can make a new release after this is merged in so that you can use this Cool New Functionality to achieve your goals ✨
> 
> Yes we are!! That would be amazing, thank you! FYI I don't think I have permission to merge, but we are happy when you are!

Okay cool! I'll go ahead and merge + push a new version up to pypi!

2023-10-03 17:45 UTC, merged

2023-10-03 17:51 UTC, jitoquinto commented
@annabaringer this is now up on pypi! - https://pypi.org/manage/project/airflow-dbt-cta/release/0.0.9/

Thank you again!!

2023-10-03 18:51 UTC, jackwelty commented
Thank you so much @jitoquinto and @emily-flambe !!